import Head from 'next/head';
import { Roboto } from 'next/font/google';
import { Heading, Text } from '@ignite-ui/react';
import HomePage from './home';

const roboto = Roboto({
	variable: '--font-roboto',
	subsets: ['latin'],
	weight: ['400', '500', '700'],
});

export default function Home() {
	return (
		<>
			<Head>
				<title>Ignite Call</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={`${roboto.className} `}>
				<HomePage />
			</div>
		</>
	);
}
